// Comprehensive Indian States, Union Territories & Cities Dataset for Matrimony App

export interface StateCitiesMap {
  [stateName: string]: string[];
}

export const INDIAN_STATES: string[] = [
  "Maharashtra",
  "Gujarat",
  "Karnataka",
  "Delhi",
  "Madhya Pradesh",
  "Telangana",
  "Tamil Nadu",
  "Rajasthan",
  "Uttar Pradesh",
  "Goa",
  "Punjab",
  "Haryana",
  "West Bengal",
  "Kerala",
  "Bihar",
  "Odisha",
  "Andhra Pradesh",
  "Assam",
  "Chhattisgarh",
  "Jharkhand",
  "Uttarakhand",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Chandigarh",
  "Puducherry",
  "Ladakh",
];

export const CITIES_BY_STATE: StateCitiesMap = {
  Maharashtra: [
    "Pune",
    "Mumbai",
    "Nashik",
    "Nagpur",
    "Chhatrapati Sambhajinagar",
    "Thane",
    "Navi Mumbai",
    "Pimpri-Chinchwad",
    "Kolhapur",
    "Solapur",
    "Amravati",
    "Sangli",
    "Nanded",
    "Jalgaon",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Satara",
    "Chandrapur",
    "Parbhani",
    "Ichalkaranji",
    "Jalna",
    "Bhusawal",
    "Panvel",
    "Yavatmal",
    "Gondia",
    "Wardha",
    "Hinganghat",
    "Washim",
    "Malegaon",
    "Ratnagiri",
    "Sindhudurg",
    "Buldhana",
    "Osmanabad",
    "Bhir (Beed)",
    "Bhandara",
    "Gadchiroli",
    "Palghar",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Junagadh",
    "Anand",
    "Navsari",
    "Bharuch",
    "Morbi",
    "Mehsana",
    "Valsad",
    "Vapi",
    "Porbandar",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Hubballi-Dharwad",
    "Mangaluru",
    "Belagavi",
    "Kalaburagi",
    "Davangere",
    "Ballari",
    "Vijayapura",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
  ],
  Delhi: [
    "New Delhi",
    "North Delhi",
    "South Delhi",
    "West Delhi",
    "East Delhi",
    "Central Delhi",
    "Noida",
    "Gurugram",
    "Faridabad",
    "Ghaziabad",
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Chhindwara",
    "Singrauli",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Khammam",
    "Karimnagar",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tiruppur",
    "Erode",
    "Vellore",
    "Tirunelveli",
    "Thanjavur",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Bharatpur",
    "Sikar",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Meerut",
    "Noida",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
  ],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Pathankot",
  ],
  Haryana: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Karnal",
    "Hisar",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Bardhaman",
    "Kharagpur",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Alappuzha",
    "Kottayam",
  ],
};

// Returns all unique cities sorted, with Maharashtra cities first
export const ALL_MAJOR_CITIES: string[] = Array.from(
  new Set(Object.values(CITIES_BY_STATE).flat())
).sort((a, b) => {
  const isAMah = CITIES_BY_STATE.Maharashtra.includes(a);
  const isBMah = CITIES_BY_STATE.Maharashtra.includes(b);
  if (isAMah && !isBMah) return -1;
  if (!isAMah && isBMah) return 1;
  return a.localeCompare(b);
});
